version: '3.8'


services:
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin
    ports: 
      - "9000:9000"
      - "9001:9001"
    entrypoint: /bin/sh
    command: -c "minio server /data --console-address ":9001""    
    tmpfs:
      - /data:size=15m

  bucketloader:
    build: ./bucketloader
    depends_on:
      - minio
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: adminadmin